apiVersion: v1
kind: Service
metadata:
  name: synapsor
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
  labels:
    app: synapsor
    app.kubernetes.io/code-repo: internal-share_synapsor
    app.kubernetes.io/name: internal-share_synapsor
spec:
  ports:
  - name: "grpc-30680"
    port: 30680
    targetPort: 30680
  - name: "grpc-30681"
    port: 30681
    targetPort: 30681
  - name: "grpc-30682"
    port: 30682
    targetPort: 30682
  - name: "grpc-30683"
    port: 30683
    targetPort: 30683
  - name: "http-9850"
    port: 9850
    targetPort: 9850
  selector:
    app: synapsor
  type: ClusterIP
status:
  loadBalancer: {}
